spring:
  # 数据库访问配置，此处使用MySQL为例。
  # 主数据源，默认的
  # 连接池配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lxb_forum?characterEncoding=utf8
    username: root
    password: 12345678
    type: org.apache.commons.dbcp2.BasicDataSource
    # 配置dbcp2
    # 初始化连接:连接池启动时创建的初始化连接数量
    dbcp2:
      initial-size: 5
      # 最大活动连接:连接池在同一时间能够分配的最大活动连接的数量, 如果设置为非正数则表示不限制
      max-active: 250
      # 最大空闲连接:连接池中容许保持空闲状态的最大连接数量,超过的空闲连接将被释放,如果设置为负数表示不限制
      max-idle: 50
      # 最小空闲连接:连接池中容许保持空闲状态的最小连接数量,低于这个数量将创建新的连接,如果设置为0则不创建
      min-idle: 5
      # 最大等待时间:当没有可用连接时,连接池等待连接被归还的最大时间(以毫秒计数),超过时间则抛出异常,如果设置为-1表示无限等待
      max-wait-millis: 10000
      # SQL查询,用来验证从连接池取出的连接,在将连接返回给调用者之前.如果指定,则查询必须是一个SQL SELECT并且必须返回至少一行记录
      validation-query: SELECT 1
      # 当建立新连接时被发送给JDBC驱动的连接参数，格式必须是 [propertyName=property;]。注意：参数user/password将被明确传递，所以不需要包括在这里。
      connection-properties: characterEncoding=utf8

  ## jpa start
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

  # redis
  cache:
    type: redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 100
        max-wait: 600
        max-idle: 100
        min-idle: 100
      shutdown-timeout: 100ms

#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
#      cluster-nodes: 127.0.0.1:9300
#      repositories:
#        enabled: true